version: '3.3'
services:
    spa:
        network_mode: web
        container_name: spa
        image: spaapp:latest
        # env_file:
        #     - .env
        environment:
            - BASEURL=$BASEURL
            - HOSTNAME=$HOSTNAME
            - KEY=$KEY
        labels: 
            - traefik.http.routers.spa.rule="Host(`$HOSTNAME`)"
            - traefik.http.routers.spa.tls="true"
            - traefik.http.routers.spa.tls.certresolver="lets-encrypt"
            - traefik.http.services.spa.loadbalancer.server.port="80"