version: '3.3'
services:
    spa:
        network_mode: web
        container_name: spa
        ports:
          - 2348:3000
        image: spaapp:latest
        # env_file:
        #     - .env
        environment:
            - BASEURL=$BASEURL
            - DNSNAME=$DNSNAME
            - KEY=$KEY
        labels: 
            - traefik.http.routers.spa.rule="Host(`$DNSNAME`)"
            - traefik.http.routers.spa.tls="true"
            - traefik.http.routers.spa.tls.certresolver="lets-encrypt"
            - traefik.http.services.spa.loadbalancer.server.port="80"